name: Continuos Integration

on:
  push:
    branches: ["master"]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Create Env File
        run: |
          mkdir -p src/environments
          cat <<EOF > src/environments/environment.ts
          export const environment = {
            production: true,
            api_url: "",
            token_name: ""
          };
          EOF

      - name: Run Install and Build
        run: |
          npm install
          npm run build
