name: Pipeline CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create environment.ts
        run: |
          mkdir -p src/environments
          cat <<EOF > src/environments/environment.ts
          export const environment = {
            baseUrl: '',
            apiUrl: '',
            tokenCookieName: '',
            techCookieName: '',
          };
          EOF

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker Compose
        run: docker compose build
